# Generated by Django 4.1.7 on 2023-03-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schoolstudent", "0002_alter_schoolinfo_user_alter_studentinfo_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolinfo",
            name="user",
        ),
        migrations.RemoveField(
            model_name="studentinfo",
            name="user",
        ),
    ]
